import axios from 'axios'
import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {Main} from '../comps/organisms/Main'
import {Countries, Country} from '../utils/models'

const Home: NextPage<Countries> = ({countries}: Countries) => {
  return (
    <div className={'flex'}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main countries={countries} />
    </div>
  )
}

export default Home

export const getStaticProps = async () => {
  const response = await axios.get('https://restcountries.com/v2/all')
  const countries: [Country] = response.data

  return {
    props: {
      countries,
    },
  }
}
