import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {Main} from '../comps/organisms/Main'

const Home: NextPage = () => {
  return (
    <div className={'flex'}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
    </div>
  )
}

export default Home
